import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from "next/link"

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Melhor grade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Bem vindo a <p className='gradient'>Melhor Grade!</p>
        </h1>

        <p className={styles.description}>
          Comece criando um cadastro:{' '}
          <code> <Link href="/visitante/cadastro">clique aqui</Link></code>
        </p>

        <p className={styles.descriptions}>
        Já tem uma conta?{' '}
          <code> <Link href="/visitante/login">clique aqui</Link></code>
        </p>
    
      </main>

      <footer className={styles.footer}>
          Trio orgânico 😎 - 2022
      </footer>
    </div>
  )
}
